package com.databb.dao;

import com.databb.entity.Basicinfo;
import com.databb.entity.BasicinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int countByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int deleteByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int insert(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int insertSelective(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	List<Basicinfo> selectByExampleWithBLOBs(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	List<Basicinfo> selectByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	int updateByExample(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	Basicinfo selectByName(String name);
}