package com.databb.dao;

import com.databb.entity.Basicinfo;
import com.databb.entity.BasicinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.databb.entity.BasicinfoKey;

public interface BasicinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int countByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int deleteByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int deleteByPrimaryKey(BasicinfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int insert(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int insertSelective(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	List<Basicinfo> selectByExampleWithBLOBs(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	List<Basicinfo> selectByExample(BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	Basicinfo selectByPrimaryKey(BasicinfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByExample(@Param("record") Basicinfo record,
			@Param("example") BasicinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByPrimaryKeySelective(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(Basicinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basicinfo
	 * @mbggenerated  Fri Mar 21 19:42:40 CST 2014
	 */
	int updateByPrimaryKey(Basicinfo record);

	Basicinfo selectByUsername(String username);
}