package com.databb.entity;

import java.util.Date;

public class Basicinfo extends BasicinfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.password
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.Name
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.birth
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private Date birth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.contact
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.email
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.photo
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private byte[] photo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.password
	 * @return  the value of basicinfo.password
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.password
	 * @param password  the value for basicinfo.password
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.Name
	 * @return  the value of basicinfo.Name
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.Name
	 * @param name  the value for basicinfo.Name
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.birth
	 * @return  the value of basicinfo.birth
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public Date getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.birth
	 * @param birth  the value for basicinfo.birth
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.contact
	 * @return  the value of basicinfo.contact
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.contact
	 * @param contact  the value for basicinfo.contact
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.email
	 * @return  the value of basicinfo.email
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.email
	 * @param email  the value for basicinfo.email
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.photo
	 * @return  the value of basicinfo.photo
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public byte[] getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.photo
	 * @param photo  the value for basicinfo.photo
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}
}