package com.databb.entity;

public class BasicinfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.username
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.Id
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	private Integer id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.username
	 * @return  the value of basicinfo.username
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.username
	 * @param username  the value for basicinfo.username
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.Id
	 * @return  the value of basicinfo.Id
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.Id
	 * @param id  the value for basicinfo.Id
	 * @mbggenerated  Fri Mar 21 14:59:53 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}
}