package com.databb.entity;

import java.util.Date;

public class Basicinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.Id
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.Name
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.birth
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	private Date birth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basicinfo.photo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	private byte[] photo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.Id
	 * @return  the value of basicinfo.Id
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.Id
	 * @param id  the value for basicinfo.Id
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.Name
	 * @return  the value of basicinfo.Name
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.Name
	 * @param name  the value for basicinfo.Name
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.birth
	 * @return  the value of basicinfo.birth
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public Date getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.birth
	 * @param birth  the value for basicinfo.birth
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basicinfo.photo
	 * @return  the value of basicinfo.photo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public byte[] getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basicinfo.photo
	 * @param photo  the value for basicinfo.photo
	 * @mbggenerated  Mon Mar 17 15:23:27 CST 2014
	 */
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}
}